disabled_rules:
  - identifier_name
  - multiple_closures_with_trailing_closure

excluded:
  - Pods

type_name:
  excluded: 
    - ios_archiApp
    - ios_archiTests
    - ios_archiUITests
    - ios_archiUITestsLaunchTests