# Rule List - https://realm.github.io/SwiftLint/rule-directory.html

# 無効にするルール
disabled_rules:
  - multiple_closures_with_trailing_closure # 複数のクロージャーの場合でも、trailing closureを利用したいため
  - empty_enum_arguments # enumの引数を省略したいため

  # opt-inルールの中で無効にするルール
  - accessibility_label_for_image #いまはアクセシビリティ対応はしないため
  - accessibility_trait_for_button #いまはアクセシビリティ対応はしないため
  - anonymous_argument_in_multiline_closure # Closureの引数を省略したいため
  - attributes # property wrapper は1行で書きたいため
  - closure_body_length # SwiftUIのViewで長くなることがあるため
  - conditional_returns_on_newline # ガード文などは簡潔に一行で記述したいため
  - discouraged_optional_collection # PHImageManagerの既存仕様のため
  - explicit_acl # できる限りACLを省略したいため
  - explicit_enum_raw_value # 暗黙的なraw値で問題ないため
  - explicit_top_level_acl # できる限りACLを省略したいため
  - explicit_type_interface # 型推論を利用したいため
  - fatal_error_message # メッセージは不要なため
  - file_header # ヘッダには特に決まりがないため
  - file_types_order # なぜか指摘されることがあるため
  - indentation_width # SwiftFormatと競合するため
  - lower_acl_than_parent # 対応不可のため
  - missing_docs #ドキュメント化を必須にしたくないため
  - no_extension_access_modifier # extension_access_modifierを優先するため
  - no_grouping_extension # グルーピングにextensionを利用したいため
  - no_magic_numbers
  - number_separator # 数字を `_` で区切りたくないため
  - object_literal # リテラルで生成したくないこともあるため
  - opening_brace # SwiftFormatと競合するため
  - required_deinit # できる限りデイニシャライザを省略したいため
  - strict_fileprivate # fileprivateを利用したいため
  - switch_case_on_newline # caseと同じ行に記述したいため
  - trailing_closure # RxSwiftのOnNextでwarningが出るため
  - vertical_parameter_alignment_on_call # なぜか指摘されることがあるため
  - vertical_whitespace_between_cases # Switch文のケース間に空白行を設けたくないため

# defaultルール以外にopt-inから採用するルール
# Pods/SwiftLint/swiftlint rules | awk -F "|" '$3 ~ "yes" && $7 ~ "no" { print $2 }' | tr -d ' ' | sed 's/^/  - /' | pbcopy
opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  # - anyobject_protocol // deprecated
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  # - inert_defer // deprecated
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_deinit
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  # - unused_capture_list // deprecated
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Pods/SwiftLint/swiftlint rules | awk -F "|" '$7 ~ "yes" { print $2 }' | tr -d ' ' | sed 's/^/  - /' | pbcopy
analyzer_rules:
  # - capture_variable
  # - explicit_self
  # - typesafe_array_init
  # - unused_declaration
  # - unused_import

included:
  - Package/Sources
  - Package/Tests
  - App

excluded:
  - Pods
  - Package/Sources/Analytics/CodeGenerated
  - Package/Sources/AppFeature/CodeGenerated
  - Package/Tests/AppFeatureTests/CodeGenerated

file_name:
  suffix_pattern: "Extensions?|\\+.*"

line_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 1 # `r` `g` `b` などを使いたいため

type_name:
  excluded: 
    - ios_archiApp
    - ios_archiTests
    - ios_archiUITests
    - ios_archiUITestsLaunchTests